tagPrefix: v

defaults {
  tag: true
  tagMessageFormat: "release {Tag}"
  includeBuildMetaData: false
  whenNoValidCommitMessages: NoIncrement
  patches: [
    RubyVersion
  ]
}

branches: [
  {
    pattern: "main"
    tag: true
    includeBuildMetaData: false
  }
]

patches: [
  {
    name: RubyVersion
    filePatterns: [
      "lib/coach_zed/version.rb"
    ]
    replacements: [
      {
        find: "VERSION = \"{VersionRegex}\""
        replace: "VERSION = \"{Version}\""
      }
    ]
  }
]

commitMessageActions: [
  {
    pattern: "BREAKING CHANGE"
    action: IncrementMajor
  }
  {
    pattern: "major(\\(.+\\))?:"
    action: IncrementMajor
  }
  {
    pattern: "feat(\\(.+\\))?:"
    action: IncrementMinor
  }
  {
    pattern: "(fix|patch)(\\(.+\\))?:"
    action: IncrementPatch
  }
]
